Metrics/LineLength:
  Max: 130

Style/Documentation:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/RescueStandardError:
  Enabled: false